# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Akademi Help
description: > # this means to ignore newlines until "baseurl:"
  Bulutfon, Lab2023 ve Netinternet geliştiricilerinin düzenli paylaşımları
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://akademi.help" # the base hostname & protocol for your site
github_username:  akademihelp

# Build settings
markdown: kramdown
permalink: /:title
sass:
  style: :compressed

# Authors Setup
author_ids: [coskuntekin, onurozgurozkan]

authors:
  coskuntekin:
    display_name: Coskun Tekin
    gravatar: 5564589155f579413c909fa1f8ad5d5b
    email: mail@coskuntekin.com
    web: http://www.coskuntekin.com/
    twitter: coskuntekin
    github: coskuntekin
  onurozgurozkan:
    display_name: Onur Ozgur Ozkan
    gravatar: 785e3d9660ae3d43f961a6fc608b9695
    email: onur.ozgur.ozkan@bulutfon.com
    web: http://www.onurozgurozkan.com
    twitter: onurozgurozkan
    github: onurozgurozkan
